language: java
sudo: required
dist: trusty
jdk:
 - oraclejdk8
matrix:
  fast_finish: true
install: skip
script: skip

before_deploy:
 - zip -r dita-json-${TRAVIS_TAG}-plugin.zip com.oxygenxml.json.dita
deploy:
  provider: releases
  api_key: ${DITA_JSON_TOKEN}
  file:
    - dita-json-${TRAVIS_TAG}-plugin.zip
  skip_cleanup: true
  on:
    tags: true
