language: java
sudo: required
dist: trusty
jdk:
 - oraclejdk8
matrix:
  fast_finish: true
install: true

before_script:
   - cd com.oxygenxml.json.dita

script:
 - ant

before_deploy:
 - cd ../
 - zip -r dita-json-${TRAVIS_TAG}-plugin.zip com.oxygenxml.json.dita
deploy:
  provider: releases
  api_key: ${DITA_JSON_TOKEN}
  file:
    - dita-json-${TRAVIS_TAG}-plugin.zip
  skip_cleanup: true
  on:
    tags: true
